package views;

import control.ControleSecretaria;
import domain.Secretaria;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

public class FrmAlterarSecretaria extends javax.swing.JFrame {
    Secretaria sec = new Secretaria();
    static Secretaria backupSecretaria = new Secretaria();
    /**
     * Creates new form FrmDeletarSecretaria
     */
    MaskFormatter formatoCpf;
    public FrmAlterarSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlDeletarPaciente = new javax.swing.JLabel();
        jbAlterarPaciente = new javax.swing.JButton();
        jbCancelarExclusaoPaciente = new javax.swing.JButton();
        try{
            formatoCpf = new MaskFormatter("###.###.###-##");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao setar a maskara" + e);
        }
        jtfAlterarSecretariaCpf = new JFormattedTextField(formatoCpf);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlDeletarPaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlDeletarPaciente.setText("INFORME O CPF DA SECRETARIA QUE DESEJA ALTERAR:");

        jbAlterarPaciente.setText("ALTERAR");
        jbAlterarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarPacienteActionPerformed(evt);
            }
        });

        jbCancelarExclusaoPaciente.setText("CANCELAR");
        jbCancelarExclusaoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarExclusaoPacienteActionPerformed(evt);
            }
        });

        jtfAlterarSecretariaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAlterarSecretariaCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlDeletarPaciente)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbAlterarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCancelarExclusaoPaciente)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jtfAlterarSecretariaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jlDeletarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfAlterarSecretariaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterarPaciente)
                    .addComponent(jbCancelarExclusaoPaciente))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-330)/2, (screenSize.height-125)/2, 330, 125);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAlterarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarPacienteActionPerformed
        backupSecretaria = null;
        this.dispose();
        //consulta o arraylist pra verificar se o secente existe e possui dados
        sec = ControleSecretaria.consultarLista(jtfAlterarSecretariaCpf.getText());
        if(sec != null){
            //realiza backup dos dados do cliente consultado anteriormente            
            backupSecretaria = sec;
            FrmTelaCadastrarSecretaria telaCadastraSecretaria = new FrmTelaCadastrarSecretaria();
            this.setLocationRelativeTo(null);
            telaCadastraSecretaria.jtfNome.setText(sec.getNome());
            telaCadastraSecretaria.jftCpf.setText(sec.getCpf());     
            if(sec.getSexo().equals("Feminino")){
                telaCadastraSecretaria.jrFeminino.setSelected(true);
            }
            if(sec.getSexo().equals("Masculino")){
                telaCadastraSecretaria.jrMasculino.setSelected(true);
            }        

            telaCadastraSecretaria.jftNascimento.setText(sec.getDataNascimento());
            telaCadastraSecretaria.jtfCidade.setText(sec.getCidade());
            telaCadastraSecretaria.jtfBairro.setText(sec.getBairro());
            telaCadastraSecretaria.jtfRua.setText(sec.getRua());
            telaCadastraSecretaria.jtfNumero.setText(sec.getNumero());                
            telaCadastraSecretaria.jcbUf.setSelectedItem(sec.getUf());        
            telaCadastraSecretaria.jftCep.setText(sec.getCep());

            telaCadastraSecretaria.jftTelefone.setText(sec.getTelefone());

            telaCadastraSecretaria.jftCelular.setText(sec.getCelular());

            telaCadastraSecretaria.jtfEmail.setText(sec.getEmail());

            telaCadastraSecretaria.setVisible(true);
            //remove o botao limpar da tela preenchida
            telaCadastraSecretaria.remove(telaCadastraSecretaria.jbLimpar);
            //desabilita o botao cpf
            telaCadastraSecretaria.jftCpf.disable();
        }
    }//GEN-LAST:event_jbAlterarPacienteActionPerformed

    private void jtfAlterarSecretariaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAlterarSecretariaCpfActionPerformed
//        cpf = jtfAlterarSecretariaCpf.getText();                
//        sec = ControleSecretaria.consultarLista(cpf);       
    }//GEN-LAST:event_jtfAlterarSecretariaCpfActionPerformed

    private void jbCancelarExclusaoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarExclusaoPacienteActionPerformed
        this.dispose();
        FrmTelaPrincipal telaPrincipal = new FrmTelaPrincipal();
        this.setLocationRelativeTo(null);
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jbCancelarExclusaoPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlterarSecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAlterarPaciente;
    private javax.swing.JButton jbCancelarExclusaoPaciente;
    private javax.swing.JLabel jlDeletarPaciente;
    private javax.swing.JTextField jtfAlterarSecretariaCpf;
    // End of variables declaration//GEN-END:variables
}
