package views;

import control.ControleDentista;
import domain.Dentista;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

public class FrmAlterarDentista extends javax.swing.JFrame {
    Dentista dent = new Dentista();
    static Dentista backupDentista = new Dentista();
    /**
     * Creates new form FrmDeletarDentista
     */
    MaskFormatter formatoCpf;
    public FrmAlterarDentista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlDeletarPaciente = new javax.swing.JLabel();
        jbAlterarPaciente = new javax.swing.JButton();
        jbCancelarExclusaoPaciente = new javax.swing.JButton();
        try{
            formatoCpf = new MaskFormatter("###.###.###-##");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao setar a maskara" + e);
        }
        jtfAlterarDentistaCpf = new JFormattedTextField(formatoCpf);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlDeletarPaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlDeletarPaciente.setText("INFORME O CPF DO DENTISTA QUE DESEJA ALTERAR:");

        jbAlterarPaciente.setText("ALTERAR");
        jbAlterarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarPacienteActionPerformed(evt);
            }
        });

        jbCancelarExclusaoPaciente.setText("CANCELAR");
        jbCancelarExclusaoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarExclusaoPacienteActionPerformed(evt);
            }
        });

        jtfAlterarDentistaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAlterarDentistaCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlDeletarPaciente)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbAlterarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCancelarExclusaoPaciente)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jtfAlterarDentistaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jlDeletarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfAlterarDentistaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterarPaciente)
                    .addComponent(jbCancelarExclusaoPaciente))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-315)/2, (screenSize.height-125)/2, 315, 125);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAlterarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarPacienteActionPerformed
        backupDentista = null;
        this.dispose();
        //consulta o arraylist pra verificar se o dentista existe e possui dados
        dent = ControleDentista.consultarLista(jtfAlterarDentistaCpf.getText());
        if(dent != null){
            //realiza backup dos dados do dentista consultado anteriormente            
            backupDentista = dent;
            FrmTelaCadastrarDentista telaCadastraDentista = new FrmTelaCadastrarDentista();
            this.setLocationRelativeTo(null);
            telaCadastraDentista.jtfNome.setText(dent.getNome());
            telaCadastraDentista.jftCpf.setText(dent.getCpf());     
            if(dent.getSexo().equals("Feminino")){
                telaCadastraDentista.jrFeminino.setSelected(true);
            }
            if(dent.getSexo().equals("Masculino")){
                telaCadastraDentista.jrMasculino.setSelected(true);
            }        
            telaCadastraDentista.jftNascimento.setText(dent.getDataNascimento());
            telaCadastraDentista.jtfCidade.setText(dent.getCidade());
            telaCadastraDentista.jtfBairro.setText(dent.getBairro());
            telaCadastraDentista.jtfRua.setText(dent.getRua());
            telaCadastraDentista.jtfNumero.setText(dent.getNumero());                
            telaCadastraDentista.jcbUf.setSelectedItem(dent.getUf());        
            telaCadastraDentista.jftCep.setText(dent.getCep());
            telaCadastraDentista.jftTelefone.setText(dent.getTelefone());
            telaCadastraDentista.jftCelular.setText(dent.getCelular());
            telaCadastraDentista.jtfEmail.setText(dent.getEmail());

            telaCadastraDentista.setVisible(true);
            //remove o botao limpar da tela preenchida
            telaCadastraDentista.remove(telaCadastraDentista.jbLimpar);
            //desabilita o botao cpf
            telaCadastraDentista.jftCpf.disable();
        }
    }//GEN-LAST:event_jbAlterarPacienteActionPerformed

    private void jtfAlterarDentistaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAlterarDentistaCpfActionPerformed
//        cpf = jtfAlterarDentistaCpf.getText();                
//        dent = ControleDentista.consultarLista(cpf);       
    }//GEN-LAST:event_jtfAlterarDentistaCpfActionPerformed

    private void jbCancelarExclusaoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarExclusaoPacienteActionPerformed
        this.dispose();
        FrmTelaPrincipal telaPrincipal = new FrmTelaPrincipal();
        this.setLocationRelativeTo(null);
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jbCancelarExclusaoPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlterarDentista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAlterarPaciente;
    private javax.swing.JButton jbCancelarExclusaoPaciente;
    private javax.swing.JLabel jlDeletarPaciente;
    private javax.swing.JTextField jtfAlterarDentistaCpf;
    // End of variables declaration//GEN-END:variables
}
