package views;

import control.ControlePaciente;
import domain.Paciente;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

public class FrmAlterarPaciente extends javax.swing.JFrame {
    
//    private FrmTelaCadastrarPaciente telaCadastraPaciente; 
    private Paciente paci;
    private ControlePaciente controlePaciente;
    MaskFormatter formatoCpf;
    public FrmAlterarPaciente() {
        initComponents();
        controlePaciente = new ControlePaciente();
        this.setLocationRelativeTo(null);
        paci = new Paciente();
          
//        FrmTelaCadastrarPaciente telaCadastraPaciente = new FrmTelaCadastrarPaciente();
//        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlDeletarPaciente = new javax.swing.JLabel();
        jbAlterarPaciente = new javax.swing.JButton();
        jbCancelarExclusaoPaciente = new javax.swing.JButton();
        try{
            formatoCpf = new MaskFormatter("###.###.###-##");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao setar a maskara" + e);
        }
        jtfAlterarPacienteCpf = new JFormattedTextField(formatoCpf);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlDeletarPaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlDeletarPaciente.setText("INFORME O CPF DO PACIENTE QUE DESEJA ALTERAR:");

        jbAlterarPaciente.setText("ALTERAR");
        jbAlterarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarPacienteActionPerformed(evt);
            }
        });

        jbCancelarExclusaoPaciente.setText("CANCELAR");
        jbCancelarExclusaoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarExclusaoPacienteActionPerformed(evt);
            }
        });

        jtfAlterarPacienteCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAlterarPacienteCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlDeletarPaciente)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbAlterarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCancelarExclusaoPaciente)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jtfAlterarPacienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jlDeletarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfAlterarPacienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterarPaciente)
                    .addComponent(jbCancelarExclusaoPaciente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAlterarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarPacienteActionPerformed
        //consulta o bd  pra verificar se o paciente existe e possui dados via cpf
        try{
            paci = controlePaciente.verificarCpfPaciente(jtfAlterarPacienteCpf.getText());

            FrmTelaAlterarPaciente telaAlteraPaciente = new FrmTelaAlterarPaciente();
            this.setLocationRelativeTo(null);
            telaAlteraPaciente.jtfNome.setText(paci.getNome());
            telaAlteraPaciente.jftCpf.setText(paci.getCpf());     
            if(paci.getSexo().equals("Feminino")){
                telaAlteraPaciente.jrFeminino.setSelected(true);
            }
            if(paci.getSexo().equals("Masculino")){
                telaAlteraPaciente.jrMasculino.setSelected(true);
            }        
            telaAlteraPaciente.jftNascimento.setText(paci.getDataNascimento());
            telaAlteraPaciente.jtfCidade.setText(paci.getCidade());
            telaAlteraPaciente.jtfBairro.setText(paci.getBairro());
            telaAlteraPaciente.jtfRua.setText(paci.getRua());
            telaAlteraPaciente.jtfNumero.setText(paci.getNumero());                
            telaAlteraPaciente.jcbUf.setSelectedItem(paci.getUf());        
            telaAlteraPaciente.jftCep.setText(paci.getCep());
            telaAlteraPaciente.jftTelefone.setText(paci.getTelefone());
            telaAlteraPaciente.jftCelular.setText(paci.getCelular());
            telaAlteraPaciente.jtfEmail.setText(paci.getEmail());

            telaAlteraPaciente.setVisible(true);
            //remove o botao limpar da tela preenchida
            //telaCadastraPaciente.remove(telaCadastraPaciente.jbLimpar);
            //desabilita o botao cpf
            telaAlteraPaciente.jftCpf.disable();
            this.dispose();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Cpf não registrado no banco de dados!\n Por favor, informe outro.");  
            jtfAlterarPacienteCpf.setText("");
            jtfAlterarPacienteCpf.setRequestFocusEnabled(true);
        }
    }//GEN-LAST:event_jbAlterarPacienteActionPerformed

    private void jtfAlterarPacienteCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAlterarPacienteCpfActionPerformed
       
    }//GEN-LAST:event_jtfAlterarPacienteCpfActionPerformed

    private void jbCancelarExclusaoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarExclusaoPacienteActionPerformed
        this.dispose();
        FrmTelaPrincipal telaPrincipal = new FrmTelaPrincipal();
        this.setLocationRelativeTo(null);
        telaPrincipal.setVisible(true);        
    }//GEN-LAST:event_jbCancelarExclusaoPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlterarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAlterarPaciente;
    private javax.swing.JButton jbCancelarExclusaoPaciente;
    private javax.swing.JLabel jlDeletarPaciente;
    public javax.swing.JTextField jtfAlterarPacienteCpf;
    // End of variables declaration//GEN-END:variables
}
