package views;

import control.ControleSecretaria;
import domain.Secretaria;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

public class FrmAlterarSecretaria extends javax.swing.JFrame {
    private Secretaria secretaria;
    private ControleSecretaria controleSecretaria;

    MaskFormatter formatoCpf;
    public FrmAlterarSecretaria() {
        initComponents();
        controleSecretaria = new ControleSecretaria();
        this.setLocationRelativeTo(null);
        secretaria = new Secretaria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlDeletarSecretaria = new javax.swing.JLabel();
        jbAlterar = new javax.swing.JButton();
        jbCancelarExclusao = new javax.swing.JButton();
        try{
            formatoCpf = new MaskFormatter("###.###.###-##");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao setar a maskara" + e);
        }
        jtfAlterarSecretariaCpf = new JFormattedTextField(formatoCpf);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlDeletarSecretaria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlDeletarSecretaria.setText("INFORME O CPF DA SECRETARIA QUE DESEJA ALTERAR:");

        jbAlterar.setText("ALTERAR");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbCancelarExclusao.setText("CANCELAR");
        jbCancelarExclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarExclusaoActionPerformed(evt);
            }
        });

        jtfAlterarSecretariaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAlterarSecretariaCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlDeletarSecretaria)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCancelarExclusao)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jtfAlterarSecretariaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jlDeletarSecretaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfAlterarSecretariaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar)
                    .addComponent(jbCancelarExclusao))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(330, 125));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        //consulta o bd  pra verificar se o secretariaente existe e possui dados via cpf
        try{
            secretaria = controleSecretaria.verificarCpfSecretaria(jtfAlterarSecretariaCpf.getText());

            FrmTelaAlterarSecretaria telaAlteraSecretaria = new FrmTelaAlterarSecretaria();
            this.setLocationRelativeTo(null);
            telaAlteraSecretaria.jtfNome.setText(secretaria.getNome());
            telaAlteraSecretaria.jftCpf.setText(secretaria.getCpf());     
            if(secretaria.getSexo().equals("Feminino")){
                telaAlteraSecretaria.jrFeminino.setSelected(true);
            }
            if(secretaria.getSexo().equals("Masculino")){
                telaAlteraSecretaria.jrMasculino.setSelected(true);
            }        
            telaAlteraSecretaria.jftNascimento.setText(secretaria.getDataNascimento());
            telaAlteraSecretaria.jtfCidade.setText(secretaria.getCidade());
            telaAlteraSecretaria.jtfBairro.setText(secretaria.getBairro());
            telaAlteraSecretaria.jtfRua.setText(secretaria.getRua());
            telaAlteraSecretaria.jtfNumero.setText(secretaria.getNumero());                
            telaAlteraSecretaria.jcbUf.setSelectedItem(secretaria.getUf());        
            telaAlteraSecretaria.jftCep.setText(secretaria.getCep());
            telaAlteraSecretaria.jftTelefone.setText(secretaria.getTelefone());
            telaAlteraSecretaria.jftCelular.setText(secretaria.getCelular());
            telaAlteraSecretaria.jtfEmail.setText(secretaria.getEmail());

            telaAlteraSecretaria.setVisible(true);
            //remove o botao limpar da tela preenchida
            //telaCadastraSecretaria.remove(telaCadastraSecretaria.jbLimpar);
            //desabilita o botao cpf
            telaAlteraSecretaria.jftCpf.disable();
            this.dispose();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Cpf não registrado no banco de dados!\n Por favor, informe outro.");  
            jtfAlterarSecretariaCpf.setText("");
            jtfAlterarSecretariaCpf.setRequestFocusEnabled(true);
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jtfAlterarSecretariaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAlterarSecretariaCpfActionPerformed
      
    }//GEN-LAST:event_jtfAlterarSecretariaCpfActionPerformed

    private void jbCancelarExclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarExclusaoActionPerformed
        this.dispose();
        FrmTelaPrincipal telaPrincipal = new FrmTelaPrincipal();
        this.setLocationRelativeTo(null);
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jbCancelarExclusaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlterarSecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelarExclusao;
    private javax.swing.JLabel jlDeletarSecretaria;
    private javax.swing.JTextField jtfAlterarSecretariaCpf;
    // End of variables declaration//GEN-END:variables
}
