package views;

public class FrmTelaPrincipal extends javax.swing.JFrame {
    //variavael para remover cliente do arraylist pelo metodo remover
    String cpf;
    /**
     * Creates new form FrmTelaPrincipal
     */
    public FrmTelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastar = new javax.swing.JMenu();
        jmiCadastrarPaciente = new javax.swing.JMenuItem();
        jmiCadastrarDentista = new javax.swing.JMenuItem();
        jmiCadastarHorario = new javax.swing.JMenuItem();
        jmiCadastaraFuncionario = new javax.swing.JMenuItem();
        jmDeletar = new javax.swing.JMenu();
        jmiDeletarPaciente = new javax.swing.JMenuItem();
        jmiDeletarDentista = new javax.swing.JMenuItem();
        jmiDeletarHorario = new javax.swing.JMenuItem();
        jmiDeletarFuncionario = new javax.swing.JMenuItem();
        jmAlterar = new javax.swing.JMenu();
        jmiAlterarPaciente = new javax.swing.JMenuItem();
        jmiAlterarDentista = new javax.swing.JMenuItem();
        jmiAlterarHorario = new javax.swing.JMenuItem();
        jmiAlteraFuncionario = new javax.swing.JMenuItem();
        jmRelatorios = new javax.swing.JMenu();
        jmiRelatorioCliente = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SSClinicas");
        setResizable(false);

        jmCadastar.setBorder(null);
        jmCadastar.setText("Cadastrar");
        jmCadastar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmCadastarMouseClicked(evt);
            }
        });

        jmiCadastrarPaciente.setText("Paciente");
        jmiCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarPacienteActionPerformed(evt);
            }
        });
        jmCadastar.add(jmiCadastrarPaciente);

        jmiCadastrarDentista.setText("Dentista");
        jmCadastar.add(jmiCadastrarDentista);

        jmiCadastarHorario.setText("Horario");
        jmCadastar.add(jmiCadastarHorario);

        jmiCadastaraFuncionario.setText("Funcionario");
        jmCadastar.add(jmiCadastaraFuncionario);

        jMenuBar1.add(jmCadastar);

        jmDeletar.setBorder(null);
        jmDeletar.setText("Deletar");
        jmDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmDeletarMouseClicked(evt);
            }
        });

        jmiDeletarPaciente.setText("Paciente");
        jmiDeletarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDeletarPacienteActionPerformed(evt);
            }
        });
        jmDeletar.add(jmiDeletarPaciente);

        jmiDeletarDentista.setText("Dentista");
        jmDeletar.add(jmiDeletarDentista);

        jmiDeletarHorario.setText("Horario");
        jmDeletar.add(jmiDeletarHorario);

        jmiDeletarFuncionario.setText("Funcionario");
        jmDeletar.add(jmiDeletarFuncionario);

        jMenuBar1.add(jmDeletar);

        jmAlterar.setBorder(null);
        jmAlterar.setText("Alterar");
        jmAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAlterarMouseClicked(evt);
            }
        });

        jmiAlterarPaciente.setText("Paciente");
        jmiAlterarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlterarPacienteActionPerformed(evt);
            }
        });
        jmAlterar.add(jmiAlterarPaciente);

        jmiAlterarDentista.setText("Dentista");
        jmAlterar.add(jmiAlterarDentista);

        jmiAlterarHorario.setText("Horario");
        jmAlterar.add(jmiAlterarHorario);

        jmiAlteraFuncionario.setText("Funcionario");
        jmAlterar.add(jmiAlteraFuncionario);

        jMenuBar1.add(jmAlterar);

        jmRelatorios.setBorder(null);
        jmRelatorios.setText("Relatorios");
        jmRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmRelatoriosMouseClicked(evt);
            }
        });

        jmiRelatorioCliente.setText("Clientes");
        jmiRelatorioCliente.setActionCommand("");
        jmiRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioClienteActionPerformed(evt);
            }
        });
        jmRelatorios.add(jmiRelatorioCliente);

        jMenuBar1.add(jmRelatorios);

        jmSair.setBorder(null);
        jmSair.setText("Sair");

        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmSair.add(jmiSair);

        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(616, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadastarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmCadastarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCadastarMouseClicked

    private void jmDeletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmDeletarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmDeletarMouseClicked

    private void jmRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmRelatoriosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmRelatoriosMouseClicked

    private void jmiCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarPacienteActionPerformed
        // TODO add your handling code here:
        FrmTelaCadastrarPaciente telaCadastraPaciente = new FrmTelaCadastrarPaciente();
        this.setLocation(400, 200);
        telaCadastraPaciente.setVisible(true);
        telaCadastraPaciente.limparCampos();       
        dispose();
    }//GEN-LAST:event_jmiCadastrarPacienteActionPerformed

    private void jmAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAlterarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmAlterarMouseClicked

    private void jmiAlterarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlterarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiAlterarPacienteActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioClienteActionPerformed
        // TODO add your handling code here:
        FrmRelatorioPacientesCadastrados frmRelatorioPacientesCadastrados = new FrmRelatorioPacientesCadastrados();
        this.setLocation(400, 200);
        frmRelatorioPacientesCadastrados.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jmiRelatorioClienteActionPerformed

    private void jmiDeletarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDeletarPacienteActionPerformed
        // TODO add your handling code here:        
        FrmDeletarPaciente frm = new FrmDeletarPaciente();
        frm.setLocation(400, 200);
        frm.setVisible(true);
    }//GEN-LAST:event_jmiDeletarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new FrmTelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAlterar;
    private javax.swing.JMenu jmCadastar;
    private javax.swing.JMenu jmDeletar;
    private javax.swing.JMenu jmRelatorios;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiAlteraFuncionario;
    private javax.swing.JMenuItem jmiAlterarDentista;
    private javax.swing.JMenuItem jmiAlterarHorario;
    private javax.swing.JMenuItem jmiAlterarPaciente;
    private javax.swing.JMenuItem jmiCadastarHorario;
    private javax.swing.JMenuItem jmiCadastaraFuncionario;
    private javax.swing.JMenuItem jmiCadastrarDentista;
    private javax.swing.JMenuItem jmiCadastrarPaciente;
    private javax.swing.JMenuItem jmiDeletarDentista;
    private javax.swing.JMenuItem jmiDeletarFuncionario;
    private javax.swing.JMenuItem jmiDeletarHorario;
    private javax.swing.JMenuItem jmiDeletarPaciente;
    private javax.swing.JMenuItem jmiRelatorioCliente;
    private javax.swing.JMenuItem jmiSair;
    // End of variables declaration//GEN-END:variables
}
